/*
    [
        {
            value:1,label:'xxx',children:[]
        },
        {
            value:1,label:'xxx',children:[
                  {
                        value:1,label:'xxx',children:[]
                  },
                  {
                        value:1,label:'xxx',children:[]
                  },
                  {
                        value:1,label:'xxx',children:[]
                  },
            ]
        },
    ]
*/